---
bucket: estuary-dev
credentials_json_sops: "ENC[AES256_GCM,data:xzy==,type:str]"
dataset: estuary
project_id: arecadata-sandbox
region: US
sops:
  kms: ~
  gcp_kms:
    - resource_id: locations/us-central1/keyRings/catalog-sops/cryptoKeys/config-encryptor
      created_at: "2024-03-09T19:33:16Z"
      enc: 
  azure_kv: ~
  hc_vault: ~
  age: ~
  lastmodified: "2024-03-09T19:33:16Z"
  mac: "ENC[AES256_GCM,data:==,type:str]"
  pgp: ~
  encrypted_suffix: _sops
  version: 3.7.3
