---
advanced:
  is_free_plan: true
api_key_id_sops: "ENC[AES256_GCM,data:v9H+Qg==,type:str]"
api_secret_key_sops: "ENC[AES256_GCM,data:==,type:str]"
feed: iex
start_date: "2024-03-08T00:00:00Z"
symbols: NVDA
sops:
  kms: ~
  gcp_kms:
    - resource_id: locations/us-central1/keyRings/catalog-sops/cryptoKeys/config-encryptor
      created_at: "2024-03-08T16:10:26Z"
      enc: CiQABM8p+yJ9kgqa8PmBoltnuiCiQ==
  azure_kv: ~
  hc_vault: ~
  age: ~
  lastmodified: "2024-03-08T16:10:26Z"
  mac: "ENC[AES256_GCM,data:bZSAAAgA==,type:str]"
  pgp: ~
  encrypted_suffix: _sops
  version: 3.7.3
